In [1]:
import numpy as np

# Check the version
print(np.__version__)

1.26.4


In [2]:
# 1-dimensonal array, also referred to as a vector
a1 = np.array([1, 2, 3])

# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [3]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [4]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [5]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [6]:
a1

array([1, 2, 3])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
import pandas as pd
df = pd.DataFrame(np.random.randint(10, size=(5, 3)), 
                                    columns=['a', 'b', 'c'])
df

a  b  c
0  6  3  4
1  6  6  2
2  6  7  8
3  8  2  6
4  8  0  6

In [10]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [11]:
df2 = pd.DataFrame(a2)
df2

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [12]:
# Create a simple array
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

In [13]:
simple_array = np.array((1, 2, 3))
simple_array, simple_array.dtype

(array([1, 2, 3]), dtype('int32'))

In [14]:
# Create an array of ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
# The default datatype is 'float64'
ones.dtype

dtype('float64')

In [16]:
# You can change the datatype with .astype()
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [17]:
# Create an array of zeros
zeros = np.zeros((5, 3, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
zeros.dtype

dtype('float64')

In [19]:
# Create an array within a range of values
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
# Random array
random_array = np.random.randint(10, size=(5, 3))
random_array

array([[8, 6, 2],
       [7, 8, 9],
       [9, 7, 6],
       [1, 8, 2],
       [5, 4, 9]])

In [21]:
# Random array of floats (between 0 & 1)
np.random.random((5, 3))

array([[0.58558379, 0.85828183, 0.89001037],
       [0.3675524 , 0.34592407, 0.11781212],
       [0.3560163 , 0.69038246, 0.68821719],
       [0.44204671, 0.01984453, 0.62180484],
       [0.40423917, 0.54142426, 0.38956293]])

In [22]:
np.random.random((5, 3))

array([[0.83686413, 0.9740019 , 0.02720184],
       [0.33975367, 0.84749361, 0.38328618],
       [0.95588846, 0.49827643, 0.81364979],
       [0.23619998, 0.11770803, 0.08588646],
       [0.07583134, 0.22239383, 0.77817284]])

In [23]:
# Random 5x3 array of floats (between 0 & 1), similar to above
np.random.rand(5, 3)

array([[0.13233625, 0.13162649, 0.68244895],
       [0.51502057, 0.44626925, 0.65988466],
       [0.21629531, 0.22654525, 0.33008675],
       [0.82358613, 0.58175225, 0.96281589],
       [0.02829486, 0.48178129, 0.15764123]])

In [24]:
np.random.rand(5, 3)

array([[0.85744742, 0.66999063, 0.30395635],
       [0.80584921, 0.18897105, 0.01612234],
       [0.75687382, 0.19918122, 0.37720293],
       [0.65876643, 0.23724071, 0.80226044],
       [0.85792076, 0.84394136, 0.50912154]])

In [25]:
# Set random seed to 0
np.random.seed(0)

# Make 'random' numbers
np.random.randint(10, size=(5, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [26]:
# Make more random numbers
np.random.randint(10, size=(5, 3))

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [27]:
# Set random seed to same number as above
np.random.seed(0)

# The same random numbers come out
np.random.randint(10, size=(5, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [28]:
np.random.seed(0)
df = pd.DataFrame(np.random.randint(10, size=(5, 3)))
df

0  1  2
0  5  0  3
1  3  7  9
2  3  5  2
3  4  7  6
4  8  8  1

In [29]:
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

  ### 3. Viewing arrays and matrices